'use strict';
const $ = id => document.getElementById(id);
const state = {selected:null, root:null, graph:null, offset:0, next:null, traceStart:null, revision:0, queueRevision:0};
const short = value => value.length > 22 ? value.slice(0,12)+'…'+value.slice(-6) : value;
const score = value => value == null ? 'Unscored' : value.toFixed(4);
const btc = value => value == null ? 'Unavailable' : (value/100000000).toFixed(8)+' BTC';
const time = value => value ? value.replace('T',' ').replace(/\.\d+\+00:00$/, ' UTC') : 'Unavailable';
function el(tag, text, cls) { const n=document.createElement(tag); if(text!=null)n.textContent=text; if(cls)n.className=cls; return n; }
function notice(message,error=false){$('notice').textContent=message;$('notice').classList.toggle('error',error);}
async function api(path){const r=await fetch('/api'+path);if(!r.ok){const b=await r.json().catch(()=>({}));throw Error(typeof b.detail==='string'?b.detail:`Request failed (${r.status}). Check your search or limits.`);}return r.json();}
function safe(fn){return (...args)=>Promise.resolve().then(()=>fn(...args)).catch(e=>{notice(e.message,true);if(!$('metrics').children.length)$('status').textContent='Unavailable · reload to retry';if($('graph-message').textContent.startsWith('Loading'))$('graph-message').textContent='Could not load graph. Retry by selecting a lead.';});}
function graphQuery(){return `hops=${$('hops').value}&max_nodes=80&max_edges=160&flagged_only=${$('graph-flagged').checked}`;}
async function queue(){const rev=++state.queueRevision;const data=await api(`/alerts?flagged_only=${$('flagged').checked}&limit=20&offset=${state.offset}`);if(rev!==state.queueRevision)return;state.next=data.next_offset;$('queue-count').textContent=data.total_matches.toLocaleString();$('queue').replaceChildren();for(const n of data.items){const b=el('button',null,'queue-row');b.dataset.id=n.id;const left=el('span',short(n.attributes.txid));left.append(el('small',time(n.timestamp)));const right=el('span',null,'right');right.append(el('span',score(n.anomaly_score),'score'),el('small',btc(n.attributes.amount_satoshis)));b.append(left,right);b.title=n.id;b.onclick=safe(()=>investigate(n.id));$('queue').append(b);}if(!data.items.length)$('queue').append(el('p','No transactions match this filter.'));$('previous').disabled=state.offset===0;$('next').disabled=state.next==null;$('page').textContent=`${data.total_matches ? state.offset+1 : 0}–${Math.min(state.offset+20,data.total_matches)}`;highlight();return data;}
function highlight(){document.querySelectorAll('[data-id]').forEach(n=>n.classList.toggle('selected',n.dataset.id===state.selected));}
function pair(list,label,value){list.append(el('dt',label),el('dd',value==null?'Unavailable':String(value)));}
function details(n){state.selected=n.id;const a=n.attributes;const box=$('details');box.replaceChildren(el('div',n.id.split(':').slice(1).join(':'),'identifier'));$('entity-type').textContent=n.type==='transaction'?'Transaction':'Observed address';const dl=el('dl');if(n.type==='transaction'){box.append(el('div','BLOCKCHAIN-STYLE OBSERVATIONS · SYNTHETIC','section-label'));for(const [label,v] of [['Timestamp',time(n.timestamp)],['Output total',btc(a.amount_satoshis)],['Amount meaning',a.amount_semantics],['Fee',btc(a.fee_satoshis)],['Input / output counts',`${a.num_inputs} / ${a.num_outputs}`],['Anomaly score',score(n.anomaly_score)],['Frozen threshold',score(n.threshold)],['Status',n.flagged==null?'No ML score available':n.flagged?'Flagged investigative lead':'Below frozen threshold'],['Model identifier',n.model_version],['Source row',a.source_row]])pair(dl,label,v);}else{for(const [label,key] of [['Connected transactions','transaction_count'],['Incoming relationships','incoming_relationship_count'],['Outgoing relationships','outgoing_relationship_count'],['Flagged connected transactions','flagged_transaction_count'],['First seen','first_seen'],['Last seen','last_seen']])pair(dl,label,a[key]);pair(dl,'Observed incoming',btc(a.total_incoming_satoshis));pair(dl,'Observed outgoing',btc(a.total_outgoing_satoshis));pair(dl,'Incoming values complete',a.incoming_value_complete);pair(dl,'Outgoing values complete',a.outgoing_value_complete);box.append(el('p','Window aggregates are observed allocations, not a wallet balance.'));}pair(dl,'Full-graph degree',a.degree);pair(dl,'Component nodes',a.component_size);box.append(dl);for(const reason of n.reasons||[])box.append(el('p',reason,'reason'));if(a.network_context){box.append(el('div','NETWORK OBSERVATION CONTEXT','section-label'));const net=el('dl');for(const [key,value]of Object.entries(a.network_context))pair(net,key.replaceAll('_',' '),value);box.append(net,el('p','Reported/synthetic context. No external GeoIP lookup or ownership inference.','hint'));}highlight();}
function showTimeline(data){const box=$('timeline');box.replaceChildren();if(data.truncated)box.append(el('p',`Partial timeline: ${data.truncation_reason}.`,'amber'));for(const n of data.timeline){const b=el('button',`${time(n.timestamp)}  ·  ${btc(n.attributes.amount_satoshis)}`);b.append(el('small',`${short(n.attributes.txid)} · ${n.flagged?'Flagged · ':''}${score(n.anomaly_score)}`));b.onclick=safe(()=>investigate(n.id));box.append(b);}if(!data.timeline.length)box.append(el('p','No transactions in this bounded view.'));}
async function selectNode(id){const rev=++state.revision;notice('Loading entity details and timeline…');const kind=id.startsWith('transaction:')?'transactions':'addresses';const [d,t]=await Promise.all([api(`/${kind}/${encodeURIComponent(id.split(':').slice(1).join(':'))}`),api(`/timeline/${encodeURIComponent(id)}?${graphQuery()}`)]);if(rev!==state.revision)return;details(d.nodes.find(n=>n.id===id));showTimeline(t);notice('Selection ready. Expand selected to follow its relationships.');}
async function investigate(id){const rev=++state.revision;state.root=id;notice('Loading bounded investigation…');$('graph-message').textContent='Loading neighbourhood…';const [g,t]=await Promise.all([api(`/graph/${encodeURIComponent(id)}?${graphQuery()}`),api(`/timeline/${encodeURIComponent(id)}?${graphQuery()}`)]);if(rev!==state.revision)return;state.graph=g;details(g.nodes.find(n=>n.id===id));render(g);showTimeline(t);$('trace-summary').textContent='Paths require strictly increasing transaction times; address linkage does not prove UTXO spends.';notice('Investigation ready · amounts include change · scores are not probabilities.');}
const ns='http://www.w3.org/2000/svg';function svg(tag,attrs){const n=document.createElementNS(ns,tag);for(const [k,v]of Object.entries(attrs))n.setAttribute(k,v);return n;}
let camera={x:0,y:0,z:1};function transform(){$('viewport').setAttribute('transform',`translate(${camera.x} ${camera.y}) scale(${camera.z})`);}function fit(){camera={x:0,y:0,z:1};transform();}
function render(data){const viewport=$('viewport');viewport.replaceChildren();fit();const nodes=data.nodes.map((n,i)=>({...n,x:450+150*Math.cos(i*2*Math.PI/data.nodes.length),y:225+150*Math.sin(i*2*Math.PI/data.nodes.length)}));const map=new Map(nodes.map(n=>[n.id,n]));const edges=data.edges.map(e=>({...e,a:map.get(e.source),b:map.get(e.target)}));
 // Deterministic bounded force layout; no animation or independent graph model.
 for(let step=0;step<180;step++){const force=nodes.map(()=>({x:0,y:0}));for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const dx=nodes[i].x-nodes[j].x,dy=nodes[i].y-nodes[j].y,d2=Math.max(60,dx*dx+dy*dy),f=1000/d2;force[i].x+=dx*f;force[i].y+=dy*f;force[j].x-=dx*f;force[j].y-=dy*f;}const index=new Map(nodes.map((n,i)=>[n.id,i]));for(const e of edges){const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,d=Math.max(1,Math.hypot(dx,dy)),f=(d-90)*.018;force[index.get(e.source)].x+=dx/d*f;force[index.get(e.source)].y+=dy/d*f;force[index.get(e.target)].x-=dx/d*f;force[index.get(e.target)].y-=dy/d*f;}nodes.forEach((n,i)=>{n.x+=Math.max(-8,Math.min(8,force[i].x+(450-n.x)*.006));n.y+=Math.max(-8,Math.min(8,force[i].y+(225-n.y)*.006));});}
 if(nodes.length){const minX=Math.min(...nodes.map(n=>n.x)),maxX=Math.max(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxY=Math.max(...nodes.map(n=>n.y));const scale=Math.min(800/Math.max(1,maxX-minX),340/Math.max(1,maxY-minY),2);nodes.forEach(n=>{n.x=450+(n.x-(minX+maxX)/2)*scale;n.y=210+(n.y-(minY+maxY)/2)*scale;});}
 if(data.ordered_node_ids?.length){const count=data.ordered_node_ids.length,columns=Math.min(12,count),rows=Math.ceil(count/columns);data.ordered_node_ids.forEach((id,i)=>{const row=Math.floor(i/columns),column=row%2?columns-1-i%columns:i%columns;map.get(id).x=55+column*790/Math.max(1,columns-1);map.get(id).y=45+row*300/Math.max(1,rows-1);});}
 for(const e of edges){const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,d=Math.max(1,Math.hypot(dx,dy));const line=svg('line',{x1:e.a.x+dx/d*13,y1:e.a.y+dy/d*13,x2:e.b.x-dx/d*16,y2:e.b.y-dy/d*16,class:'edge'+(data.ordered_edge_ids?.includes(e.id)?' path':''),'marker-end':'url(#arrow)'});const title=svg('title',{});title.textContent=`${e.type} allocation · ${btc(e.amount_satoshis)} · ${e.attributes.allocation_count} allocation(s)`;line.append(title);viewport.append(line);}
 for(const n of nodes){const g=svg('g',{class:'node','data-id':n.id,transform:`translate(${n.x} ${n.y})`,tabindex:0,role:'button','aria-label':n.id});const fill=n.type==='address'?'#647c99':n.flagged?'#f3b35b':n.anomaly_score==null?'#77838f':'#58c9e3';const shape=n.type==='address'?svg('circle',{r:10}):svg('rect',{x:-10,y:-10,width:20,height:20,rx:3,transform:'rotate(45)'});shape.setAttribute('class','shape');shape.setAttribute('fill',fill);shape.setAttribute('stroke','#152538');const title=svg('title',{});title.textContent=`${n.id}\n${n.timestamp?time(n.timestamp)+'\n':''}${n.type==='transaction'?btc(n.attributes.amount_satoshis)+' · Score '+score(n.anomaly_score):n.attributes.transaction_count+' connected transactions'}`;g.append(shape,title);if(nodes.length<=35||n.id===state.selected){const text=svg('text',{y:28,'text-anchor':'middle'});text.textContent=short(n.id.split(':')[1]);g.append(text);}g.onclick=safe(()=>selectNode(n.id));g.onkeydown=safe(e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();return selectNode(n.id);}});viewport.append(g);}
 $('graph-count').textContent=`${nodes.length} nodes · ${edges.length} relationships`;$('graph-message').textContent=data.truncated?`Bound reached: ${data.truncation_reason}. Showing a partial graph.`:data.found===false?'No chronological path found within search bounds.':`${data.hops||'Path'} ${data.hops?'hop view · one hop = one directed relationship':''}`;highlight();}
const graph=$('graph');let drag=null;graph.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;drag={x:e.clientX,y:e.clientY,cx:camera.x,cy:camera.y};graph.setPointerCapture(e.pointerId);});graph.addEventListener('pointermove',e=>{if(!drag)return;const ratio=900/graph.getBoundingClientRect().width;camera.x=drag.cx+(e.clientX-drag.x)*ratio;camera.y=drag.cy+(e.clientY-drag.y)*ratio;transform();});graph.addEventListener('pointerup',()=>drag=null);graph.addEventListener('pointercancel',()=>drag=null);function zoom(f){const z=Math.max(.3,Math.min(5,camera.z*f));camera.x=450-(450-camera.x)*z/camera.z;camera.y=225-(225-camera.y)*z/camera.z;camera.z=z;transform();}graph.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?1.12:1/1.12);},{passive:false});
$('zoom-in').onclick=()=>zoom(1.25);$('zoom-out').onclick=()=>zoom(.8);$('fit').onclick=fit;
$('expand').onclick=safe(()=>{if(!state.selected)throw Error('Select an entity first.');return investigate(state.selected);});$('hops').onchange=$('graph-flagged').onchange=safe(()=>state.root&&investigate(state.root));$('flagged').onchange=safe(()=>{state.offset=0;return queue();});$('refresh').onclick=safe(queue);$('previous').onclick=safe(()=>{state.offset=Math.max(0,state.offset-20);return queue();});$('next').onclick=safe(()=>{if(state.next!=null){state.offset=state.next;return queue();}});
let searchRevision=0;$('search-form').onsubmit=safe(async e=>{e.preventDefault();const rev=++searchRevision;const q=$('search').value.trim();if(!/^[A-Za-z0-9:_-]{2,150}$/.test(q))throw Error('Enter at least two letters or digits from a TXID or address.');const d=await api('/search?q='+encodeURIComponent(q));if(rev!==searchRevision)return;$('search-results').replaceChildren();for(const n of d.items){const b=el('button',`${n.type} · ${short(n.id.split(':')[1])}`);b.title=n.id;b.onclick=safe(()=>investigate(n.id));$('search-results').append(b);}notice(d.items.length?`${d.total_matches} match(es)${d.truncated?' · showing first 20; refine your search':''}. Select a result.`:'No matching observations.');if(d.items.length===1)await investigate(d.items[0].id);});
$('trace-start').onclick=()=>{if(!state.selected){notice('Select an entity first.',true);return;}state.traceStart=state.selected;$('trace-label').textContent='From '+short(state.traceStart.split(':')[1]);};$('trace').onclick=safe(async()=>{if(!state.traceStart||!state.selected)throw Error('Set a trace start and select a destination first.');const rev=++state.revision;notice('Searching a bounded chronological path…');const d=await api(`/trace?source=${encodeURIComponent(state.traceStart)}&target=${encodeURIComponent(state.selected)}&max_hops=100`);if(rev!==state.revision)return;state.graph=d;render(d);$('trace-summary').textContent=d.sequence_summary.reason||'No chronological sequence found within the search bounds.';const byId=new Map(d.nodes.map(n=>[n.id,n]));showTimeline({...d,timeline:d.sequence.map(n=>byId.get('transaction:'+n.txid))});notice(d.truncated?`Trace limited: ${d.truncation_reason}. Absence of a path does not prove disconnection.`:'Chronological trace complete.');});
safe(async()=>{await api('/health');const d=await api('/overview');$('status').textContent='Offline · Ready';for(const [title,value,sub]of [['Transactions',d.total_transactions,d.dataset_identifier],['Observed addresses',d.total_addresses,'No ownership clustering'],['Flagged transactions',d.flagged_transactions,d.flagged_percentage.toFixed(1)+'% · frozen threshold'],['Graph relationships',d.graph_edges,'Directed input / output allocations']]){const card=el('article',null,'metric');card.append(el('span',title,'eyebrow'),el('strong',value.toLocaleString()),el('small',sub));$('metrics').append(card);}const q=await queue();notice(d.score_status==='unavailable'?'Ready without ML scores. Turn off Flagged only to browse observations.':'Ready · frozen model '+(d.model_identifiers[0]?.split(':')[0]||'unavailable'));if(q.items.length)await investigate(q.items[0].id);})().catch(()=>{});
